### ISSUE TITLE
Images uri

### ISSUE THREAD

**Issue by rocks860** [ymane/BSMultiPicker#1]
Thank you for this sweet picker. I finally integrated it with my project, and no errors at the moment.
But I am a little confused about retrieving the 6 images uri.
The way I know it is
if(requestCode == GALLERY_REQUEST && resultCode == RESULT_OK){ mSelectedUri = data.getData(); }
But here in onMultiImageSelected(List<Uri> uriList, String tag) it's an image view, and I don't know how to get ivImage1 ivImage2 ivImage3 ivImage4 ivImage5 ivImage6
I hope you can help me, thank you

**Comment by ymane** [comment]
hi,
Thank u for using my library.
 for MultiImageSelect u need to implement interface BSMultiPicker.OnMultiImageSelectedListener and overwride method 
`public void onMultiImageSelected(List<Uri> uriList) {
mSelectedUri1  = uriList.get(0);
mSelectedUri2  = uriList.get(1); 
mSelectedUri3  = uriList.get(2);
....
.....
....
....
mSelectedUri10  = uriList.get(9);

 }`
u can get 6 images uri in uriList you can get like above .
in mSelectedUri1   get first image uri and mSelectedUri2  get second image uri .

**Comment by rocks860** [comment]
Thank you, also, the camera on multiselect is only overriding, it's basically a singleselect.
So it doesn't work

**Comment by ymane** [comment]
for singleselect u need to implement interface BSMultiPicker.OnSingleImageSelectedListener and overwride method
`  @Override
    public void onSingleImageSelected(Uri uri) {
         mSelectedUri1 =uri;
     }`

**Comment by rocks860** [comment]
I think you miss understood me. What I am saying is that the camera is not working on mutiselect.
The camera takes one picture, and if you try to take a second picture it just overrides the first one.
